"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const projectRoot = path.resolve(__dirname, "..");
const distRoot = path.join(projectRoot, "dist");
const clientRoot = path.join(distRoot, "client");
const serverRoot = path.join(distRoot, "server");

const MIME_TYPES = {
  ".css": "text/css; charset=utf-8",
  ".gif": "image/gif",
  ".html": "text/html; charset=utf-8",
  ".ico": "image/x-icon",
  ".jpeg": "image/jpeg",
  ".jpg": "image/jpeg",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".mp3": "audio/mpeg",
  ".png": "image/png",
  ".svg": "image/svg+xml; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".wasm": "application/wasm",
  ".webmanifest": "application/manifest+json; charset=utf-8",
  ".webp": "image/webp",
};

function listFiles(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const absolutePath = path.join(directory, entry.name);
    return entry.isDirectory() ? listFiles(absolutePath) : [absolutePath];
  });
}

function copyDirectory(source, destination) {
  for (const sourceFile of listFiles(source)) {
    const destinationFile = path.join(destination, path.relative(source, sourceFile));
    fs.mkdirSync(path.dirname(destinationFile), { recursive: true });
    fs.copyFileSync(sourceFile, destinationFile);
  }
}

function toRoute(relativePath) {
  return `/${relativePath.split(path.sep).join("/")}`;
}

function buildAssetRecord(relativePath) {
  const absolutePath = path.join(projectRoot, relativePath);
  const contents = fs.readFileSync(absolutePath);
  return {
    route: toRoute(relativePath),
    mimeType: MIME_TYPES[path.extname(relativePath).toLowerCase()] || "application/octet-stream",
    body: contents.toString("base64"),
    etag: `\"${crypto.createHash("sha256").update(contents).digest("hex")}\"`,
  };
}

fs.rmSync(distRoot, { recursive: true, force: true });
fs.mkdirSync(clientRoot, { recursive: true });
fs.mkdirSync(serverRoot, { recursive: true });

fs.copyFileSync(path.join(projectRoot, "index.html"), path.join(clientRoot, "index.html"));
copyDirectory(path.join(projectRoot, "src"), path.join(clientRoot, "src"));
const publicAssets = ["麒麟.jpg", "掘开.jpg", "旭旭宝宝.jpg", "发牌.mp3", "出牌.mp3", "点牌.mp3", "背景音乐.mp3"];
publicAssets.forEach((asset) => fs.copyFileSync(path.join(projectRoot, asset), path.join(clientRoot, asset)));

const relativeAssets = [
  "index.html",
  ...publicAssets,
  ...listFiles(path.join(projectRoot, "src")).map((filePath) => path.relative(projectRoot, filePath)),
];
const assets = relativeAssets.map(buildAssetRecord);
const indexAsset = assets.find((asset) => asset.route === "/index.html");
assets.push({ ...indexAsset, route: "/" });

const workerSource = `// Generated by scripts/build-sites.js. Do not edit dist directly.
const ASSETS = new Map(${JSON.stringify(
  assets.map(({ route, ...asset }) => [route, asset]),
)});

function decodeBase64(value) {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  return bytes;
}

const worker = {
  async fetch(request) {
    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method Not Allowed", {
        status: 405,
        headers: { Allow: "GET, HEAD" },
      });
    }

    const url = new URL(request.url);
    let requestPath = url.pathname;
    try { requestPath = decodeURIComponent(requestPath); } catch (error) { /* keep original path */ }
    const asset = ASSETS.get(requestPath);
    if (!asset) {
      return new Response("Not Found", {
        status: 404,
        headers: { "Content-Type": "text/plain; charset=utf-8" },
      });
    }

    if (request.headers.get("If-None-Match") === asset.etag) {
      return new Response(null, { status: 304, headers: { ETag: asset.etag } });
    }

    const isDocument = requestPath === "/" || requestPath.endsWith(".html");
    const headers = new Headers({
      "Cache-Control": isDocument ? "no-cache" : "public, max-age=86400",
      "Content-Type": asset.mimeType,
      ETag: asset.etag,
      "X-Content-Type-Options": "nosniff",
    });
    const body = request.method === "HEAD" ? null : decodeBase64(asset.body);
    return new Response(body, { status: 200, headers });
  },
};

export default worker;
`;

fs.writeFileSync(path.join(serverRoot, "index.js"), workerSource, "utf8");
fs.writeFileSync(path.join(serverRoot, "package.json"), '{"type":"module"}\n', "utf8");

console.log(`Built ${assets.length} routes for Sites.`);
